import { app } from 'electron'
import { join, dirname } from 'path'
import { homedir } from 'os'
import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, appendFileSync } from 'fs'

interface SkillLoaderTarget {
  name: string
  path: string
  enabled: boolean
}

interface SkillLoaderInput {
  targets?: string | SkillLoaderTarget[]
  mcpPort?: number
}

// ─── Agent Layer reader (inline to avoid cross-module import issues) ──────────

function getAgentLayerDir(): string {
  return join(app.getPath('userData'), 'agent')
}

function readMarkdownDir(dir: string): { path: string; content: string }[] {
  if (!existsSync(dir)) return []
  const results: { path: string; content: string }[] = []
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isFile() && entry.name.endsWith('.md')) {
        const filePath = join(dir, entry.name)
        try {
          results.push({ path: filePath, content: readFileSync(filePath, 'utf-8') })
        } catch {
          // skip
        }
      }
    }
  } catch {
    // ignore
  }
  return results
}

function stripFrontmatter(content: string): string {
  return content.replace(/^---\n[\s\S]*?\n---\n?/, '').trim()
}

function extractTitle(content: string, filename: string): string {
  const match = content.match(/^#\s+(.+)/m)
  return match ? match[1] : filename.replace('.md', '')
}

// ─── Context generation ───────────────────────────────────────────────────────

function generateContextFile(mcpPort: number): string {
  const agentDir = getAgentLayerDir()
  const timestamp = new Date().toISOString()
  const mcpUrl = `http://localhost:${mcpPort}`

  const lines: string[] = [
    `<!-- Generated by Life Console Skill Loader at ${timestamp} -->`,
    '',
    '# Life Console Context',
    '',
    `> MCP Server: ${mcpUrl}/sse`,
    '> Use the MCP tools below to query your knowledge base and agent layer.',
    ''
  ]

  // Axioms section
  const axioms = readMarkdownDir(join(agentDir, 'axioms'))
  if (axioms.length > 0) {
    lines.push('## Your Axioms (Decision Principles)')
    lines.push('')
    for (let i = 0; i < axioms.length; i++) {
      const body = stripFrontmatter(axioms[i].content)
      const title = extractTitle(body, axioms[i].path.split('/').pop() ?? '')
      lines.push(`${i + 1}. **${title}**`)
      // include brief content (first non-heading paragraph)
      const paragraphs = body
        .replace(/^#.+$/m, '')
        .split('\n\n')
        .map((p) => p.trim())
        .filter(Boolean)
      if (paragraphs.length > 0) {
        lines.push(`   ${paragraphs[0].replace(/\n/g, ' ')}`)
      }
    }
    lines.push('')
  }

  // Methodologies section
  const methodologies = readMarkdownDir(join(agentDir, 'methodologies'))
  if (methodologies.length > 0) {
    lines.push('## Your Methodologies')
    lines.push('')
    for (const m of methodologies) {
      const body = stripFrontmatter(m.content)
      const title = extractTitle(body, m.path.split('/').pop() ?? '')
      // Include up to first 500 chars of content
      const brief = body.replace(/^#.+\n?/m, '').trim().slice(0, 500)
      lines.push(`### ${title}`)
      lines.push(brief)
      if (body.length > 500) lines.push('...')
      lines.push('')
    }
  }

  // MCP tool usage
  lines.push('## MCP Tools Available')
  lines.push('')
  lines.push('Connect to the Life Console MCP Server to access:')
  lines.push(`- \`listAxioms(category?)\` — list all axioms, optionally filter by category`)
  lines.push(`- \`getMethodology(topic)\` — get the most relevant methodology for a topic`)
  lines.push(`- \`searchKnowledge(query, limit?)\` — full-text search across knowledge base`)
  lines.push(`- \`getCard(id)\` — get a specific knowledge card by ID`)
  lines.push('')
  lines.push(
    'When relevant, call `searchKnowledge()` to retrieve detailed knowledge cards on specific topics.'
  )

  return lines.join('\n')
}

// ─── Target writers ───────────────────────────────────────────────────────────

const CLAUDE_SECTION_MARKER = '<!-- life-console-start -->'
const CLAUDE_SECTION_END = '<!-- life-console-end -->'

function writeClaudeCodeTarget(contextContent: string): void {
  const claudeDir = join(homedir(), '.claude')
  const claudeMdPath = join(claudeDir, 'CLAUDE.md')

  mkdirSync(claudeDir, { recursive: true })

  const newSection = `${CLAUDE_SECTION_MARKER}\n${contextContent}\n${CLAUDE_SECTION_END}`

  if (!existsSync(claudeMdPath)) {
    writeFileSync(claudeMdPath, newSection + '\n', 'utf-8')
    return
  }

  let existing = readFileSync(claudeMdPath, 'utf-8')

  // Replace existing life-console section
  const sectionRegex = new RegExp(
    `${CLAUDE_SECTION_MARKER}[\\s\\S]*?${CLAUDE_SECTION_END}`,
    'g'
  )

  if (sectionRegex.test(existing)) {
    existing = existing.replace(sectionRegex, newSection)
    writeFileSync(claudeMdPath, existing, 'utf-8')
  } else {
    appendFileSync(claudeMdPath, '\n\n' + newSection + '\n', 'utf-8')
  }
}

function writeCursorTarget(targetPath: string, contextContent: string): void {
  const dir = dirname(targetPath)
  mkdirSync(dir, { recursive: true })
  writeFileSync(targetPath, contextContent, 'utf-8')
}

function writeGenericTarget(targetPath: string, contextContent: string): void {
  const dir = dirname(targetPath)
  mkdirSync(dir, { recursive: true })
  writeFileSync(targetPath, contextContent, 'utf-8')
}

// ─── Main skill function ──────────────────────────────────────────────────────

export default async function run(
  input: SkillLoaderInput
): Promise<{ writtenPaths: string[]; errors: string[] }> {
  const mcpPort = input.mcpPort ?? 7777

  let targets: SkillLoaderTarget[] = []

  if (input.targets) {
    if (typeof input.targets === 'string') {
      try {
        targets = JSON.parse(input.targets)
      } catch {
        return { writtenPaths: [], errors: ['Invalid targets JSON'] }
      }
    } else {
      targets = input.targets
    }
  }

  targets = targets.filter((t) => t.enabled)

  if (targets.length === 0) {
    return { writtenPaths: [], errors: ['No enabled targets configured'] }
  }

  const contextContent = generateContextFile(mcpPort)
  const writtenPaths: string[] = []
  const errors: string[] = []

  for (const target of targets) {
    try {
      if (target.name === 'claude-code') {
        writeClaudeCodeTarget(contextContent)
        writtenPaths.push(join(homedir(), '.claude', 'CLAUDE.md'))
      } else if (target.name === 'cursor') {
        writeCursorTarget(target.path, contextContent)
        writtenPaths.push(target.path)
      } else {
        writeGenericTarget(target.path, contextContent)
        writtenPaths.push(target.path)
      }
    } catch (err) {
      errors.push(`Failed to write ${target.name}: ${String(err)}`)
    }
  }

  return { writtenPaths, errors }
}
